// Code generated by go2go; DO NOT EDIT.


//line option.go2:1
package api

//line option.go2:1
import (
//line option.go2:1
 "errors"
//line option.go2:1
 "testing"
//line option.go2:1
)

//line option.go2:1
type Importable୦ int

//line option.go2:1
var _ = errors.As
//line option.go2:1
var _ = testing.AllocsPerRun
